### ISSUE TITLE
can't find ./setup_dependencies.sh

### ISSUE THREAD

**Issue by dotrungkien3210** [IABTechLab/uid2-operator#224]
Hello IAB team
i can't see setup_dependencies.sh file. so i can start the first step
can anyone help me send link to install that file

**Comment by sunnywu** [comment]
Hi @dotrungkien3210 apology for late reply. the instruction on setup_dependencies.sh  is outdated and no longer required. I have updated our [readme.md](https://github.com/IABTechLab/uid2-operator)  and you can refer to it again and just run an operator instance by executing 

`mvn clean compile exec:java -Dvertx-config-path=conf/integ-config.json`

**Comment by sunnywu** [comment]
apology for late reply. we have updated the the instruction on [readme.md](https://github.com/IABTechLab/uid2-operator) and you can refer to it again and just run an operator instance by executing
`mvn clean compile exec:java -Dvertx-config-path=conf/integ-config.json`

`setup_dependencies.sh` is outdated and no longer required. 

thanks.
